config/routes.rb
Air::Application.routes.draw do
  
  resources :airports

  resources :reservations

  get "/profile" => 'users#profile', :as => :profile
  
  get "sessions/new", :as => :signin
  post "sessions/create"
  get "sessions/destroy", :as => :signout

  resources :users

  get "flights/index" => 'flights#index', :as => :flights

  root to: 'flights#index'
  
  get '/mockup' => 'pages#home'
  get '/help' => 'pages#help', :as => :help
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :card_number, :departs_on, :flight_id, :user_id
  
  belongs_to :flight
  belongs_to :user
  belongs_to :passenger, :class_name => 'User', :foreign_key => :user_id
  
  validates :card_number, :presence => true
  validates :departs_on, :presence => true
  validates :card_number, :format => { :with => /^4\d{15}/ }
  
  after_create :increase_frequent_flyer_miles
  after_destroy :decrease_frequent_flyer_miles
  
  def decrease_frequent_flyer_miles
    if self.user
      self.user.miles_earned -= self.flight.distance
      self.user.save
    end
  end
  # CHALLENGE: As a user, when I cancel a reservation,
  # it should be removed from my profile
  # and my frequent flyer miles should decrease.
  
  
  def increase_frequent_flyer_miles
    self.user.miles_earned += self.flight.distance
    self.user.save
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  before_filter :require_admin, :only => [:index, :show]
  
  def require_admin
    if session[:user_id].nil? || !User.find_by_id(session[:user_id]).admin? 
      redirect_to root_url, notice: 'You must be an admin to see that!'
    end
  end
  
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new
    @reservation.flight = Flight.find_by_id(params[:flight_id])
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])
    @reservation.user = User.find_by_id(session[:user_id])
    
    respond_to do |format|
      if @reservation.save
        
        email = ReservationMailer.confirm(@reservation)
        email.deliver
        
        # @reservation.user.miles_earned += @reservation.flight.distance
        # @reservation.user.save
        
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to user_url(@reservation.user) }
      format.json { head :no_content }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :flight_id %>
  
  <div class="field">
    <%= f.label :card_number, "Give Us Your Moolah" %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :departs_on %><br />
    <%= f.date_select :departs_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<div id="moolah">
  <p>We've made <%= number_to_currency(Reservation.count * 70) %> so far!</p>
</div>


<table>
  <tr>
    <th>Flight</th>
    <th>User</th>
    <th>Card number</th>
    <th>Departs on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.flight.number %></td>
    <td><%= reservation.user.name %></td>
    <td><%= reservation.card_number %></td>
    <td><%= reservation.departs_on %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>Flight #<%= @reservation.flight.number %></h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
  <b>Flight:</b>
  <%= @reservation.flight.number %>
  <p>From: <%= @reservation.flight.departure_airport_code %></p>
  <p>To: <%= @reservation.flight.arrival_airport_code %></p>
  <p>On: <%= @reservation.departs_on %></p>
</p>

<p>
  <b>Card number:</b>
  <%= @reservation.card_number %>
</p>

<p>
  <b>Departs on:</b>
  <%= @reservation.departs_on %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>