config/routes.rb
Air::Application.routes.draw do
  
  resources :airports

  resources :reservations

  get "/profile" => 'users#profile', :as => :profile
  
  get "sessions/new", :as => :signin
  post "sessions/create"
  get "sessions/destroy", :as => :signout

  resources :users

  get "flights/index" => 'flights#index', :as => :flights

  root to: 'flights#index'
  
  get '/mockup' => 'pages#home'
  get '/help' => 'pages#help', :as => :help
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Academy Air</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div id="container">
		<header>
			<h1><%= link_to "Academy Air", root_url %></h1>
			<nav>
				<ul>
					<% if session[:user_id] %>
						<li><%= link_to "View My Profile", profile_url %></li>
						<li><%= link_to "Help", help_url %></li>
						<li><%= link_to "Sign Out", signout_url %></li>
					<% else %>
						<li><%= link_to "Sign Up", new_user_url %></li>
						<li><%= link_to "Sign In", signin_url %></li>
						<li><%= link_to "Help", help_url %></li>
					<% end %>
				</ul>
			</nav>
			<p>
			  <% if session[:user_id] %>
			    <% u = User.find_by_id(session[:user_id]) %>
			    Hello, <%= u.name %>
			 <% end %>
			</p>
		</header>

		<div id="content">
			<%= yield %>
		</div>
		
		<footer>
			&copy;2012 Academy Air, Inc.  Got comments or suggestions? Keep 'em to yourself!
		</footer>
	</div>
</body>
</html>